// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvgjoenejdmgmfuxynfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2Z2pvZW5lamRtZ21mdXh5bmZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDI3MDgsImV4cCI6MjA2MDU3ODcwOH0.fZN7k9KOeoI9MSVriCJW_OQlcvhaNCtti9PvByPQvcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);